### ISSUE TITLE
Support for other browsers than firefox

### ISSUE THREAD

**Issue by sclassen** [asciidoctor/asciidoctorj-screenshot#1]
Currently only Firefox is supported. Allow to configure the browser.

**Comment by fix** [comment]
Well, the only reason i have chosen firefox is because the viewport was more predictable in that time.

**Comment by sclassen** [comment]
New version 0.2.0 released. The new version does no longer include Firefox Webdriver.
Instead the webdriver for your browser needs to be specified in your build script.

See https://github.com/sclassen/asciidoctorj-screenshot-example for both gradle and maven example
