### ISSUE TITLE
Tutorial needed

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctorj-screenshot#12]
this plugin seems to be quite helpful, however, I don't manage to set it up.

A quick guide on how to set it up would be great.

**Comment by sclassen** [comment]
Maybe I find some time over the holidays.
Can you give me a hint on how your project is setup, so I can tailor the guide accordingly.

Are you using Maven or Gradle?

**Comment by rdmueller** [comment]
Gradle on windows 10.
I tried to add your lugin as a dependency the same way as I added the pdf or diagram plugin. nothing happened.
then I checked out your example. It ran and started firefox but firefox did not navigate to a page.

Maybe I also find some time to investigate further and try it with ubuntu...

**Comment by sclassen** [comment]
Firefox is not navigating because the screenshot plugin uses an outdated version of selenium webdriver.
I need to change how web driver is provided to the plugin in order to be able to keep up with the fast rhythm at which new webdriver versions are released.
see also #11 and #9

**Comment by bcouetil** [comment]
+1, seems very helpful, I'm really looking forward to having it working again 😃

**Comment by sclassen** [comment]
New version 0.2.0 released. The new version does no longer include Firefox Webdriver.
Instead the webdriver for your browser needs to be specified in your build script.

See https://github.com/sclassen/asciidoctorj-screenshot-example for both gradle and maven example

Feel free to close this issue if the new version and the examples helped to get your build running

**Comment by rdmueller** [comment]
thanx!

**Comment by bcouetil** [comment]
@sclassen, thank you for your time, right when I need this.

But the updated maven example does not work on my PC :
`A required class was missing while executing org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc: geb/Browser`

I suspect a missing dependency, as one is a duplicate of another : 
https://github.com/sclassen/asciidoctorj-screenshot-example/blob/master/maven/pom.xml

**Comment by bcouetil** [comment]
Adding this solved the problem.

```
<dependency>
    <groupId>org.gebish</groupId>
    <artifactId>geb-core</artifactId>
    <version>0.10.0</version>
</dependency>
```

**Comment by sclassen** [comment]
@bcouetil Adding `geb` as a dependency manually should not be necessary.
If you have a look at the pom.xml of the screenshot extension it already includes geb.

If this behavior persist and you can reproduce it with a pom.xml which you can share with me, then please open an separate issue for this

https://bintray.com/asciidoctor/maven/download_file?file_path=org%2Fasciidoctor%2Fasciidoctorj-screenshot%2F0.2.0%2Fasciidoctorj-screenshot-0.2.0.pom
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.asciidoctor</groupId>
  <artifactId>asciidoctorj-screenshot</artifactId>
  <version>0.2.0</version>
  <dependencies>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.4.16</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.asciidoctor</groupId>
      <artifactId>asciidoctorj</artifactId>
      <version>1.5.8.1</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.gebish</groupId>
      <artifactId>geb-core</artifactId>
      <version>2.3</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <name>asciidoctorj-screenshot</name>
  <url>https://github.com/asciidoctor/asciidoctorj-screenshot</url>
  <inceptionYear>2016</inceptionYear>
  <licenses>
    <license>
      <name>MIT</name>
      <url>https://opensource.org/licenses/MIT</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <scm>
    <url>https://github.com/asciidoctor/asciidoctorj-screenshot.git</url>
  </scm>
  <developers>
    <developer>
      <id>sclassen</id>
      <name>Stephan Classen</name>
      <roles>
        <role>Developer</role>
      </roles>
    </developer>
    <developer>
      <id>madmas</id>
      <name>Markus Schlichting</name>
      <roles>
        <role>Developer</role>
      </roles>
    </developer>
  </developers>
</project>
```

**Comment by bcouetil** [comment]
Indeed, but you restrict it at the runtime, and my error is at compile time...
