### ISSUE TITLE
[Bug] screenshot directory problem

### ISSUE THREAD

**Issue by bcouetil** [asciidoctor/asciidoctorj-screenshot#14]
Hello again.

I'm still using Maven.

My image dir : `<imagesdir>./images</imagesdir>`

The screenshots are written in `target/generated-docs/screenshots`

The generated HTML says the image is there `src="./images/screenshots/asciidoctorj-screenshot.png"`

With the extra `/images` in path, it is not displaying...

Did I miss something ?

**Comment by sclassen** [comment]
You can configure into which directory the extension places the images.
I forgot to include this in the example.

Look at the updated pom.xml int the maven example and search for the `screenshot-dir-name`

**Comment by bcouetil** [comment]
Thank you.

So I added `<screenshot-dir-name>images/screenshots</screenshot-dir-name>`
Screenshots are indeed in this directory now.

But now the HTML says `src="./images/images/screenshots/asciidoctorj-screenshot.png"`

Still the imagesdir getting in the way.

**Comment by sclassen** [comment]
:grin: 
I check it out tomorrow

**Comment by sclassen** [comment]
I added support for the `imagesdir` attribute.
Check out the new version 0.2.2

**Comment by bcouetil** [comment]
Just tested under 0.2.2, it works like I charm, thank you 😄
