### ISSUE TITLE
Allow to scale image

### ISSUE THREAD

**Issue by sclassen** [asciidoctor/asciidoctorj-screenshot#15]
as @bcouetil mentions in # 13 (https://github.com/asciidoctor/asciidoctorj-screenshot/issues/13#issuecomment-454701600)

It would be nice if the screenshot could be scaled by asciidoctor after it was taken.

```
screenshot::${url}[dimension=1024x780,width=600]
```
Where `dimension` is interpreted by the screenshot extension and `width` is passed to the converter to do the scaling

**Comment by sclassen** [comment]
available as of version 0.3.0

**Comment by bcouetil** [comment]
Tested, thanks 😄
