### ISSUE TITLE
Expand attributes in extension

### ISSUE THREAD

**Issue by sclassen** [asciidoctor/asciidoctorj-screenshot#3]
Asciidoctor does not expand the attributes (variables) for extensions.
This needs to be done at least for the URL in the screenshot macro.
Maybe we need to also do this for the content of the geb block

**Comment by sclassen** [comment]
@lordofthejars Do you think we need to do this also for the geb block?
Or would it be sufficient to add a target to the geb block (similar to the screenshot macro) so that we do not need to search the entire geb code for the attributes

```
[geb, url={mySite}]
// no need to 'go' to site, as url parameter will cause an implicit 'go'. And the {mySite} would be expanded like in the screenshot macro
$('#button').click()
```

**Comment by lordofthejars** [comment]
yes I think that in every place where Asciidoctor does not expand the attributes, it should be done. In this case you mean the attributes value of a geb block

**Comment by sclassen** [comment]
yes maybe it is easier to just do it in the attributes of the geb block and not in the entire block content. because the content is in the end groovy code we would need to ensure that we do not accidentally expand some groovy block.

**Comment by lordofthejars** [comment]
Yes I think the same.

**Comment by mojavelinux** [comment]
I think that block attributes are expanded, as long as you surround the value in single quotes:

```
[geb, url='{mySite}']
```

Asciidoctor doesn't expand attributes in the target or attributes of a block macro, though. In those cases, you have to expand them explicitly.

In the future, we may have a declarative way to control this behavior. It wasn't something I considered when I first wrote the parser.

**Comment by mojavelinux** [comment]
Keep in mind that it is necessary to pass on the subs attribute. For instance,

```
[geb,subs=attributes+]
```

Asciidoctor Diagram recently dealt with this issue. See https://github.com/asciidoctor/asciidoctor-diagram/issues/105

**Comment by sclassen** [comment]
I added a bunch of integration tests and substitution is now working fine except for the geb block content.
Especially if it is a literal block.
I will try to get a hold of some groovy guys at my workplace to see how we can expand attributes within groovy code. The tricky part is to distinguish attributes from closures...

**Comment by sclassen** [comment]
@lordofthejars I opened a pull request with tests and some refactoring for the attribute expansion. Can you have a look at it. Thx

**Comment by mojavelinux** [comment]
> I will try to get a hold of some groovy guys at my workplace to see how we can expand attributes within groovy code.

One thing you might be able to do is pass the document attribute map to Groovy and allow the use of Groovy syntax for referencing those attributes. Something like:

```
[geb]
$("input", name: "q").value("${attrs['asciidoctor-version']}")
waitFor(5){true}
```

In other words, you are exposing the attribute map to Grovoy. This would work without modifying the subs on the block.

**Comment by sclassen** [comment]
@mojavelinux thanks for the hint. It works like a charm
expanding of attributes has been merged with pull request #7

**Comment by mojavelinux** [comment]
Cool!

I had a chance to review the PR. I'd like to make a suggestion. The variable adocAttrs doesn't feel very elegant to me. Since you are using uppercase for Browser, Dimension, Keys, perhaps you can bind to the variable Attributes instead (implied that they are from AsciiDoc). I'd also be open to Attrs. wdyt?

I also noticed that you are substituting attributes using a custom routine. We should set it as a goal in the future to use the `AbstractNode#apply_subs` method once AsciidoctorJ makes it available. All the logic for performing substitutions, attributes or otherwise, is handled by this method.

**Comment by sclassen** [comment]
The difference between Browser, Dimension, Keys on one side and the attributes on the other side is that for Browser, Dimension, Keys I am binding the class object where as for attributes I bind an instance object.

The difference is that `Keys.ENTER` will refer to the static field `ENTER` where as `adocAttrs.get('foo')` refers to the instance method `get()`

I was considering calling them just 'attributes' or 'attrs' but that felt to generic and I was afraid this could lead to name collision. That is why I have chosen the more verbose 'adocAttrs'.

One could though argue that the geb code is written specifically for the documentation and therefore it can adapt to the naming convention given by the screenshot extension. Do you think this is a legitimate restriction to put onto the users?

**Comment by mojavelinux** [comment]
I now see the distinction from the class names. However, I still think a more readable variable name should be chosen. I like "attrs" or "attributes". I think it's pretty clear given the uniqueness of that term that it is coming from AsciiDoc.

**Comment by mojavelinux** [comment]
Another idea is to use the variable name "asciidoc", which is understood to be a map of variables.

**Comment by sclassen** [comment]
I like asciidoc it is both, simple and specific. No extra fuzz and also little chance for name collision

**Comment by mojavelinux** [comment]
:+1:
