### ISSUE TITLE
Browser not closed

### ISSUE THREAD

**Issue by lordofthejars** [asciidoctor/asciidoctorj-screenshot#6]
When executing asciidoctor task for generating screenshots but with Gradle Daemon enabled, the browser is not closed after the documentation is generated.

I have executed asciidoctor task first with daemon enabled and I noticed this behaviour, then I executed the same task but with daemon disabled and it worked, so it seems that this is the cause of the problem since it has been the only difference.

**Comment by sclassen** [comment]
Good catch. Thank you
I have the daemon turned off because it caused weired behavior when I was developing the screenshot extension. But the behavior you describe gave me some new insight.
I think we may need to register a post processor which closes the GEB resources (i.e. the browser).

**Comment by sclassen** [comment]
@lordofthejars I added a post processor to close the browser after the document has been processed.
can you verify if the behavior is fixed in the current HEAD

**Comment by sclassen** [comment]
closing as there is no feedback
